# Generated by Django 4.1 on 2022-11-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypdfs',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mypdfs',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyDocs',
        ),
        migrations.DeleteModel(
            name='Mypdfs',
        ),
    ]
