# Generated by Django 4.1 on 2022-11-30 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dms', '0002_remove_mypdfs_type_remove_mypdfs_user_delete_mydocs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myeditor',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myeditor',
            name='effectivedate',
            field=models.DateField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='myeditor',
            name='expirydate',
            field=models.DateField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Mypdfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Document', max_length=100, null=True)),
                ('pdf', models.FileField(blank=True, upload_to='user_uploads/pdf/')),
                ('parties', models.CharField(blank=True, max_length=100, null=True)),
                ('term', models.CharField(blank=True, max_length=1000, null=True)),
                ('liabilitycap', models.CharField(blank=True, max_length=1000, null=True)),
                ('consideration', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('effectivedate', models.DateField(blank=True, max_length=1000, null=True)),
                ('expirydate', models.DateField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank='True', max_length=100, null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.filetype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Document', max_length=100, null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='user_uploads/docx/')),
                ('parties', models.CharField(blank=True, max_length=100, null=True)),
                ('term', models.CharField(blank=True, max_length=1000, null=True)),
                ('liabilitycap', models.CharField(blank=True, max_length=1000, null=True)),
                ('consideration', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('effectivedate', models.DateField(blank=True, max_length=1000, null=True)),
                ('expirydate', models.DateField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.filetype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
