# Generated by Django 4.1 on 2022-12-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0003_alter_myeditor_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypdfs',
            name='type',
        ),
    ]
