# Generated by Django 4.1 on 2022-12-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_remove_mypdfs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypdfs',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='user_uploads/pdf/'),
        ),
    ]
