# Generated by Django 4.1 on 2023-01-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0005_alter_mypdfs_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypdfs',
            name='pdf',
            field=models.FileField(upload_to='user_uploads/pdf/'),
        ),
        migrations.DeleteModel(
            name='Esign',
        ),
    ]
